# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sc-curso',
                'doc_host': 'https://twistin.github.io',
                'git_url': 'https://github.com/twistin/sc-curso',
                'lib_path': 'sc_curso'},
  'syms': {'sc_curso.core': {'sc_curso.core.foo': ('core.html#foo', 'sc_curso/core.py')}}}
